# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  glfw_config = debug
  glad_config = debug
  freetype_config = debug
  lua_config = debug
  TypedEngine_config = debug
  TypedEditor_config = debug
endif
ifeq ($(config),release)
  glfw_config = release
  glad_config = release
  freetype_config = release
  lua_config = release
  TypedEngine_config = release
  TypedEditor_config = release
endif

PROJECTS := glfw glad freetype lua TypedEngine TypedEditor

.PHONY: all clean help $(PROJECTS) Dependencies

all: $(PROJECTS)

Dependencies: freetype glad glfw lua

glfw:
ifneq (,$(glfw_config))
	@echo "==== Building glfw ($(glfw_config)) ===="
	@${MAKE} --no-print-directory -C TypedEngine/external/glfw -f Makefile config=$(glfw_config)
endif

glad:
ifneq (,$(glad_config))
	@echo "==== Building glad ($(glad_config)) ===="
	@${MAKE} --no-print-directory -C TypedEngine/external/glad -f Makefile config=$(glad_config)
endif

freetype:
ifneq (,$(freetype_config))
	@echo "==== Building freetype ($(freetype_config)) ===="
	@${MAKE} --no-print-directory -C TypedEngine/external/freetype -f Makefile config=$(freetype_config)
endif

lua:
ifneq (,$(lua_config))
	@echo "==== Building lua ($(lua_config)) ===="
	@${MAKE} --no-print-directory -C TypedEngine/external/lua -f Makefile config=$(lua_config)
endif

TypedEngine: glad freetype lua glfw
ifneq (,$(TypedEngine_config))
	@echo "==== Building TypedEngine ($(TypedEngine_config)) ===="
	@${MAKE} --no-print-directory -C TypedEngine -f Makefile config=$(TypedEngine_config)
endif

TypedEditor: TypedEngine glad freetype lua glfw
ifneq (,$(TypedEditor_config))
	@echo "==== Building TypedEditor ($(TypedEditor_config)) ===="
	@${MAKE} --no-print-directory -C TypedEditor -f Makefile config=$(TypedEditor_config)
endif

clean:
	@${MAKE} --no-print-directory -C TypedEngine/external/glfw -f Makefile clean
	@${MAKE} --no-print-directory -C TypedEngine/external/glad -f Makefile clean
	@${MAKE} --no-print-directory -C TypedEngine/external/freetype -f Makefile clean
	@${MAKE} --no-print-directory -C TypedEngine/external/lua -f Makefile clean
	@${MAKE} --no-print-directory -C TypedEngine -f Makefile clean
	@${MAKE} --no-print-directory -C TypedEditor -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   glfw"
	@echo "   glad"
	@echo "   freetype"
	@echo "   lua"
	@echo "   TypedEngine"
	@echo "   TypedEditor"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"